### ISSUE TITLE
Error when downloading file: file_operations_error: couldn't create output path: /storage/emulated/0/SongTube

### ISSUE THREAD

**Issue by dylancl** [SongTube/SongTube-App#127]
After installing the app and trying to download (or convert) any file, I get this error. After making the folder myself, the error changes to

```
file_operations_error: /storage/emulated/0/Android/data/com.artxdev.songtube/files/#Y.9thStreet Beezy - Blood On Da Leaves Freestyle (Official Video) Shot by @JDOT_TV_MEDIA.ogg java.io.IOException: Operation not permitted
    at java.io.UnixFileSystem.createFileExclusively0(Native Method)
    at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
    at java.io.File.createNewFile(File.java:1008)
    at com.artxdev.file_operations.FileOperationsPlugin.moveFile(FileOperationsPlugin.java:5)
    at com.artxdev.file_operations.FileOperationsPlugin.access$000(FileOperationsPlugin.java:1)
    at com.artxdev.file_operations.FileOperationsPlugin$1.run(FileOperationsPlugin.java:6)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
```

The device is a Mi 9T running MIUI 12. SongTube has all permissions, including read/write permissions (I doublechecked).

**Comment by Artx-II** [comment]
Does this issue always happens or is it specific to that song?

**Comment by Clashkid155** [comment]
For me it's seem to be the new norm.

**Comment by dylancl** [comment]
> Does this issue always happens or is it specific to that song?

This happens for every video that I try to download.

**Comment by darkgeekrocker** [comment]
> > Does this issue always happens or is it specific to that song?
> 
> This happens for every video that I try to download.

I was having the same issue/error, i find that setting the pathway for downloads to "downloads" fixed it.

**Comment by animegamer4422** [comment]
Me too it and happens for every Video/Audio I try to download
I also tried changing the Download location and gave it permissions to access the folder 
But the error still happens
Btw the device I'm using is Asus Rog 3

**Comment by Artx-II** [comment]
Updated repo with the new project. It works now.
