### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by NSTAdventure** [SongTube/SongTube-App#170]
FATAL EXCEPTION: pool-6-thread-1
Process: com.artxdev.songtube, PID: 21163
java.lang.IllegalArgumentException: The given URL is not valid
 at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeStreamLinkHandlerFactory.getId(YoutubeStreamLinkHandlerFactory.java:46)
 at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeStreamLinkHandlerFactory.onAcceptUrl(YoutubeStreamLinkHandlerFactory.java:1)
 at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(LinkHandlerFactory.java:1)
 at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:6)
 at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:4)
 at com.artxdev.newpipeextractor_dart.youtube.YoutubeLinkHandler.getIdFromStreamUrl(YoutubeLinkHandler.java:2)
 at com.artxdev.newpipeextractor_dart.NewpipeextractorDartPlugin$1.run(NewpipeextractorDartPlugin.java:8)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)

realme 5i
android 10 Realme UI 1.0
songtube 6.4.3

**Comment by Artx-II** [comment]
Repository was updated with the new project. Fixed by now.
