### ISSUE TITLE
Building app from source generates "Error running pod install"

### ISSUE THREAD

**Issue by rlsgitmas** [SongTube/SongTube-App#260]
I am trying to build the app for macos

### Steps to reproduce

1. Download Source code .zip file  
2. unzip 
3. open unzipped folder in VSCode 

4.  run commad in terminal `flutter build macos`

```
The plugin `flutter_ffmpeg` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin
supports the Android V2 embedding. Otherwise, consider removing it since a future release of
Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2
embedding: https://flutter.dev/go/android-plugin-migration.

Updating minimum macOS deployment target to 10.14.
Upgrading project.pbxproj
Upgrading Podfile
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Removing script build phase dependency analysis.
Running pod install...                                             363ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    [!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find
    `Runner`.

    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer/target_inspector.rb:108:in `compute_targets'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer/target_inspector.rb:40:in `compute_results'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:1197:in `block (3 levels) in inspect_targets_to_integrate'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:1195:in `each'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:1195:in `block (2 levels) in inspect_targets_to_integrate'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:1193:in `each'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user
    _interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:1188:in `inspect_targets_to_integrate'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller/analyzer.rb:107:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller.rb:422:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller.rb:244:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user
    _interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller.rb:243:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/inst
    aller.rb:162:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/comm
    and/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:
    334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/comm
    and.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/bin/pod:55:in
    `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in `<main>'
Error running pod install
```

# Tried the following to fix errors `dart fix --apply`
The following errors appear :

```
Computing fixes in songtube...  
Error from the analysis server: Exception while getting bulk fixes: Exception generating fix for unnecessary_string_escapes in /Users/rxa/Downloads/songtube/lib/languages/translations/languageDe.dart
Bad state: Can't create both a dart file edit and a generic file edit for the same file
#0      ChangeBuilderImpl.addGenericFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:166:7)
#1      RemoveUnnecessaryStringEscape.compute (package:analysis_server/src/services/correction/dart/remove_unnecessary_string_escape.dart:32:19)
#2      BulkFixProcessor._applyProducer (package:analysis_server/src/services/correction/bulk_fix_processor.dart:297:22)
#3      BulkFixProcessor._generateFix (package:analysis_server/src/services/correction/bulk_fix_processor.dart:734:11)
#4      BulkFixProcessor._bulkApply (package:analysis_server/src/services/correction/bulk_fix_processor.dart:313:15)
#5      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:618:15)
#6      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:521:15)
<asynchronous suspension>
#7      BulkFixProcessor._computeFixes (package:analysis_server/src/services/correction/bulk_fix_processor.dart:369:11)
<asynchronous suspension>
#8      EditBulkFixes.handle (package:analysis_server/src/handler/legacy/edit_bulk_fixes.dart:45:20)
<asynchronous suspension>
#9      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:552:11)
<asynchronous suspension>
#10     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#11     LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:533:7)
<asynchronous suspension>


#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:653:7)
<asynchronous suspension>
#1      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:521:9)
<asynchronous suspension>
#2      BulkFixProcessor._computeFixes (package:analysis_server/src/services/correction/bulk_fix_processor.dart:369:11)
<asynchronous suspension>
#3      EditBulkFixes.handle (package:analysis_server/src/handler/legacy/edit_bulk_fixes.dart:45:20)
<asynchronous suspension>
#4      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:552:11)
<asynchronous suspension>
#5      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#6      LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:533:7)
<asynchronous suspension>


#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:653:7)
<asynchronous suspension>
#1      BulkFixProcessor._fixErrorsInLibrary (package:analysis_server/src/services/correction/bulk_fix_processor.dart:521:9)
<asynchronous suspension>
#2      BulkFixProcessor._computeFixes (package:analysis_server/src/services/correction/bulk_fix_processor.dart:369:11)
<asynchronous suspension>
#3      EditBulkFixes.handle (package:analysis_server/src/handler/legacy/edit_bulk_fixes.dart:45:20)
<asynchronous suspension>
#4      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:552:11)
<asynchronous suspension>
#5      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#6      LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:533:7)
<asynchronous suspension>
```

OS version:
MacOS 14.2.1

IDE:
VSCode 

Flutter:
Flutter 3.16.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ef1af02aea (5 days ago) • 2024-01-11 15:19:26 -0600
Engine • revision 4a585b7929
Tools • Dart 3.2.4 • DevTools 2.28.5

### Expected behavior

1. Download Source code .zip file  
2. unzip 
3. open vscode 

4.  run commad in terminal `flutter build macos` or `dart fix --apply`

6. No errors appear

### Actual behavior

Error happens when trying to build from source

### SongTube version

10.2.0-4000

### Android version

Android 12

### Other details

I would like to build the app for other platforms such as linux and MacOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
This app is not meant to run on macOS, many libraries including the core extractor supports Android only.

Closing this since there is no support for other platforms.
