### ISSUE TITLE
[Bug] Error while downloading file

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#37]
I am facing 2 issues while downloading files. Though Scaffold is `successful` with the starting message of 'download started...' I get this error log,

```bash
======== Exception caught by widgets library =======================================================
The following StateError was thrown building DefaultTextStyle(debugLabel: whiteMountainView subtitle1, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip):
Bad state: Stream has already been listened to.


The relevant error-causing widget was: 
  Scaffold-[String <'this'>] .../screens/home.dart:23:12
When the exception was thrown, this was the stack: 
#4      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:138:38)
#5      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:112:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4845:57)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4682:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3660:14)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
Bad state: Stream has already been listened to.
The relevant error-causing widget was: 
  Scaffold-[LabeledGlobalKey<ScaffoldState>#de07a] .../lib.dart:151:14
====================================================================================================


======== Exception caught by widgets library =======================================================
Bad state: Stream has already been listened to.
The relevant error-causing widget was: 
  Scaffold-[String <'this'>] .../screens/home.dart:23:12
====================================================================================================
```

Though this stack makes file moves to downloadable queue, it never gets completed. It always stuck at `Clearing Existing Metadata...`

**Comment by Clashkid155** [comment]
Never had this issue, did you add something.

**Comment by bohrasankalp** [comment]
@Artx-II any idea for this issue?

**Comment by Artx-II** [comment]
I couldn't reproduce this issue, can you share your Android version and more details of what you tried to download? Does this issue prevents you from downloading?

**Comment by bohrasankalp** [comment]
Yes, my downloading never gets complete.  It always stuck with message ``. 

Flutter 1.22.5 • channel origin/stable • remotes
Engine • revision ae90085a84
Tools • Dart 2.10.4
Android version: 10QKQ1
MI Phones.

**Comment by Artx-II** [comment]
This shouldn't happen anymore, if the problem persist then feel free to re-open this issue.
